#! /bin/bash -e

### BEGIN INIT INFO
# Provides:          teu_worker
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts teuthology worker
# Description:       starts nginx using start-stop script
### END INIT INFO

if ! [ $# -eq 1 ]
then
echo "Usage: \$0 [start|stop|restart|status]"
exit 1
fi

start() {
 START_STATUS=$(ps uax | grep ceph | grep tube | grep -v grep | awk '{print $1,$2,$12,$16,$17,$18,$19}')
 if [ -z "$START_STATUS" ];
  then
        echo "Starting worker ..."
        cd /home/teuthworker
        sudo -u teuthworker "/home/teuthworker/bin/start.sh"
        START_STATUS=$(ps uax | grep ceph | grep tube | grep -v grep)
             if [ -z "$START_STATUS" ];
              then
                    echo "       *  fail"
              else
                    echo "       *  done"
             fi
  else
       echo "    *  teuthology worker is already running"
       echo $STATUS
 fi
}


stop() {
 echo "Stopping worker ..."
 ps uax | grep ceph | grep tube | grep -v grep | awk '{print $2}' | xargs kill -9
 echo "  *  done"
}


status() {
 STATUS=$(ps uax | grep ceph | grep tube | grep -v grep | awk '{print $1,$2,$12,$16,$17,$18,$19}')
 if [ -z "$STATUS" ];
  then
       echo "    *  teuthology worker is not running"
  else
       echo "    *  teuthology worker is running"
       echo $STATUS
 fi
}


case "$1" in
 start)
 start
;;
 stop)
 stop
;;
 restart)
 stop
 start
;;
 status)
 status
;;
esac

